
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package SyntacticAnalyzer;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LBRACKET = 37;
  public static final int GE = 29;
  public static final int SLASH = 32;
  public static final int CASE = 20;
  public static final int REM = 23;
  public static final int LPAREN = 33;
  public static final int INTERFACE = 17;
  public static final int FOR = 13;
  public static final int MINUS = 3;
  public static final int STAR = 25;
  public static final int RPAREN = 34;
  public static final int SEMICOLON = 7;
  public static final int AND = 4;
  public static final int LT = 27;
  public static final int TYPE = 18;
  public static final int OR = 30;
  public static final int COMMA = 6;
  public static final int PLUS = 2;
  public static final int IF = 11;
  public static final int DOT = 5;
  public static final int LE = 26;
  public static final int EOF = 0;
  public static final int BOOLEAN = 8;
  public static final int RETURN = 19;
  public static final int RBRACKET = 38;
  public static final int error = 1;
  public static final int NUMBER = 21;
  public static final int NEQ = 24;
  public static final int EQ = 31;
  public static final int SWITCH = 12;
  public static final int LBRACE = 36;
  public static final int FUNC = 10;
  public static final int DEFAULT = 9;
  public static final int RBRACE = 35;
  public static final int STRING = 22;
  public static final int STRUCT = 15;
  public static final int GT = 28;
  public static final int VAR = 14;
  public static final int FALLTHROUGH = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "AND",
  "DOT",
  "COMMA",
  "SEMICOLON",
  "BOOLEAN",
  "DEFAULT",
  "FUNC",
  "IF",
  "SWITCH",
  "FOR",
  "VAR",
  "STRUCT",
  "FALLTHROUGH",
  "INTERFACE",
  "TYPE",
  "RETURN",
  "CASE",
  "NUMBER",
  "STRING",
  "REM",
  "NEQ",
  "STAR",
  "LE",
  "LT",
  "GT",
  "GE",
  "OR",
  "EQ",
  "SLASH",
  "LPAREN",
  "RPAREN",
  "RBRACE",
  "LBRACE",
  "LBRACKET",
  "RBRACKET"
  };
}

