/* The following code was generated by JFlex 1.3.5 on 25/07/17 01:02 */

package LexicalAnalyzer; // pacote ao qual pertencerÃ¡ a classe gerada pelo jflex

import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.ComplexSymbolFactory;
import java.io.IOException;
import java_cup.runtime.Symbol;
import SyntacticAnalyzer.sym;
import java.io.FileInputStream;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 25/07/17 01:02 from the specification file
 * <tt>file:/C:/Users/nilo.DESKTOP-GUAFK5S/Documents/LFT2017/PasitoCompilador/src/LexicalAnalyzer/Pasito.jflex</tt>
 */
public class LexicalAnalyzer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int CODESEG = 2;
  final public static int YYINITIAL = 0;
  final public static int ST_STRING = 1;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\4\1\1\1\0\1\4\1\1\22\0\1\4\1\35\1\15"+
    "\2\0\1\30\1\31\1\0\1\42\1\43\1\3\1\26\1\40\1\27"+
    "\1\16\1\2\12\7\1\0\1\41\1\33\1\34\1\32\2\0\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\2\6\1\6\1\6\1\6\1\6"+
    "\1\6\1\6\1\6\1\6\1\6\1\6\1\6\1\6\6\6\1\46"+
    "\1\56\1\47\3\0\1\22\1\50\1\37\1\51\1\10\1\52\1\14"+
    "\1\25\1\13\2\6\1\21\1\6\1\17\1\20\1\36\1\6\1\12"+
    "\1\24\1\11\1\23\1\55\1\53\1\6\1\54\1\6\1\44\1\5"+
    "\1\45\uff82\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    47,    94,    94,    94,   141,    94,   188,   235,   282, 
      329,    94,   376,   423,    94,    94,    94,   470,   517,   564, 
      611,   658,   705,    94,    94,    94,    94,    94,    94,    94, 
       94,   752,   799,   846,   893,   940,   940,    94,   987,  1034, 
     1081,    94,  1128,  1175,  1222,    94,  1269,  1316,  1363,    94, 
       94,    94,    94,    94,  1410,  1457,  1504,  1551,  1598,  1645, 
     1692,    94,    94,    94,    94,  1739,  1786,  1833,    94,  1880, 
     1927,  1974,  2021,  2068,    94,  2115,  2162,    94,    94,  2209, 
     2256,  2303,    94,  2350,  2397,  2444,    94,  2491,  2538,  2585, 
     2632,  2679,  2726,  2773,    94,    94,  2820,  2867,  2914,  2961, 
       94,    94,  3008,  3055,  3102,    94,  3149,  3196,    94
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\4\1\5\1\6\1\7\1\5\1\10\1\4\1\11"+
    "\1\4\1\12\1\4\1\13\1\4\1\14\1\15\5\4"+
    "\1\16\1\4\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\4\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\2\4"+
    "\1\43\1\4\1\44\1\0\3\44\2\45\1\44\5\45"+
    "\1\46\1\44\7\45\10\44\2\45\10\44\6\45\1\47"+
    "\61\0\1\50\1\51\60\0\1\52\60\0\1\11\6\0"+
    "\1\53\114\0\1\54\21\0\1\55\32\0\1\56\13\0"+
    "\1\53\6\0\1\57\51\0\1\60\41\0\1\61\34\0"+
    "\1\62\61\0\1\63\56\0\1\64\56\0\1\65\56\0"+
    "\1\66\44\0\1\67\54\0\1\70\46\0\1\71\66\0"+
    "\1\72\1\0\1\73\1\74\55\0\1\75\34\0\1\44"+
    "\1\0\13\44\1\0\40\44\12\0\1\76\1\77\2\0"+
    "\1\100\1\0\1\101\40\0\1\5\1\102\2\0\1\5"+
    "\54\0\1\5\62\0\1\53\105\0\1\103\31\0\1\104"+
    "\63\0\1\105\52\0\1\106\57\0\1\107\67\0\1\110"+
    "\52\0\1\111\110\0\1\112\16\0\1\113\65\0\1\114"+
    "\54\0\1\115\60\0\1\116\37\0\1\50\64\0\1\117"+
    "\56\0\1\120\71\0\1\121\44\0\1\122\55\0\1\123"+
    "\67\0\1\124\57\0\1\125\55\0\1\126\74\0\1\127"+
    "\31\0\1\130\103\0\1\131\56\0\1\132\27\0\1\133"+
    "\71\0\1\134\44\0\1\135\117\0\1\136\15\0\1\137"+
    "\72\0\1\140\53\0\1\141\55\0\1\142\62\0\1\143"+
    "\53\0\1\144\53\0\1\145\50\0\1\146\57\0\1\147"+
    "\103\0\1\150\37\0\1\151\46\0\1\152\71\0\1\153"+
    "\47\0\1\154\67\0\1\155\31\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  8,  9,  9,  1,  9,  1,  1,  1,  1,  9,  1,  1,  9,  9, 
     9,  1,  1,  1,  1,  1,  1,  9,  9,  9,  9,  9,  9,  9,  9,  1, 
     1,  1,  1,  1,  1,  9,  1,  0,  0,  9,  1,  0,  0,  9,  0,  0, 
     0,  9,  9,  9,  9,  9,  0,  0,  0,  0,  0,  0,  0,  9,  9,  9, 
     9,  0,  0,  0,  9,  0,  0,  0,  0,  0,  9,  0,  0,  9,  9,  0, 
     0,  0,  9,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  9,  9, 
     0,  0,  0,  0,  9,  9,  0,  0,  0,  9,  0,  0,  9
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	
    private ComplexSymbolFactory symbolFactory;

    public StringBuffer string = new StringBuffer();
    

    /*
    * Construtor utilizado na chamada do analisador lÃ©xico pelo CUP
    * @param sf instÃ¢ncia da fÃ¡brica de sÃ­mbolos implementada pelo CUP que usaremos
    * @param is instÃ¢ncia do arquivo de entrada em Pasito que serÃ¡ analisado
    */
    public LexicalAnalyzer(ComplexSymbolFactory sf, FileInputStream is) {
        this(is);
        symbolFactory = sf;
    }
    public LexicalAnalyzer(ComplexSymbolFactory sf, java.io.Reader reader) {
        this(reader);
        symbolFactory = sf;
    }

    /*
    * Retorna de sÃ­mbolos identificados pelo analisador lÃ©xico
    * O sÃ­mbolo retornado Ã© um objeto da classe ComplexSymbolFactory implementada pelo CUP
    * TambÃ©m Ã© retornada a localizaÃ§Ã£o do sÃ­mbolo no arquivo, Ãºtil para fins de feedback ao usuÃ¡rio sobre a  posiÃ§Ã£o do erro (caso haja)
    * VocÃªs provavelmente vÃ£o precisar sobrecarregar essa funÃ§Ã£o para cobrir todos os tipos de sÃ­mbolo q vcs precisam retornar
    */
    public Symbol symbol(String nome, int code) {
    	
    	System.out.println("<" + nome + ", " + yytext() + "> (" + yyline + " - " + yycolumn + ")");
    	
        return symbolFactory.newSymbol(nome, code,
                            new Location(yyline+1, yycolumn+1, yychar),
                            new Location(yyline+1, yycolumn+yylength(), yychar+yylength()));
    }
	
	public Symbol symbol(String nome, int code, Object val) {
    	
    	System.out.println("<" + nome + ", " + yytext() + "> (" + yyline + " - " + yycolumn + ")");
    	
        return symbolFactory.newSymbol(nome, code,
                            new Location(yyline+1, yycolumn+1, yychar),
                            new Location(yyline+1, yycolumn+yylength(), yychar+yylength()));
    }
    
    	public Symbol symbol(String nome, int code, String val) {
    	
    	System.out.println("<" + nome + ", " + val + "> (" + yyline + " - " + yycolumn + ")");
    	
        return symbolFactory.newSymbol(nome, code,
                            new Location(yyline+1, yycolumn+1, yychar),
                            new Location(yyline+1, yycolumn+yylength(), yychar+yylength()));
    }

    /*
    * Emite um feedback no console com mensagem de erro, posiÃ§Ã£o e caractere
    */
    protected void emit_warning(String message){
        System.out.println("lexicalAnalyzer warning: " + message + " at : 2 "+
                (yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexicalAnalyzer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public LexicalAnalyzer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[3243];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 164) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 82: 
          {  return symbol("CASE",CASE);  }
        case 110: break;
        case 77: 
          {  return symbol("VAR", VAR);  }
        case 111: break;
        case 74: 
          {  return symbol("FOR", FOR);  }
        case 112: break;
        case 68: 
          {  return symbol("DOT", DOT);  }
        case 113: break;
        case 16: 
          {  return symbol("REM", REM);  }
        case 114: break;
        case 35: 
          {  string.append( yytext() );  }
        case 115: break;
        case 49: 
          {  return symbol("AND", AND);  }
        case 116: break;
        case 53: 
          {  return symbol("NEQ", NEQ);  }
        case 117: break;
        case 86: 
          {  return symbol("FUNC", FUNC);  }
        case 118: break;
        case 78: 
          {  return symbol("TYPE", TYPE);  }
        case 119: break;
        case 6: 
          {  return symbol("STAR", STAR);  }
        case 120: break;
        case 14: 
          {  return symbol("PLUS", PLUS);  }
        case 121: break;
        case 4: 
        case 7: 
          {   }
        case 122: break;
        case 51: 
          {  return symbol("LE",LE);  }
        case 123: break;
        case 11: 
          { 
									string.setLength(0);
                                    yybegin(ST_STRING);
                                 }
        case 124: break;
        case 19: 
          {  return symbol("LT", LT);  }
        case 125: break;
        case 18: 
          {  return symbol("GT", GT);  }
        case 126: break;
        case 41: 
          {  return symbol("OR", OR);  }
        case 127: break;
        case 45: 
          {  return symbol("IF", IF);  }
        case 128: break;
        case 50: 
          {  return symbol("GE", GE);  }
        case 129: break;
        case 52: 
          {  return symbol("EQ", EQ);  }
        case 130: break;
        case 38: 
          {  string.append('\\');  }
        case 131: break;
        case 61: 
          {  string.append('\t');  }
        case 132: break;
        case 62: 
          {  string.append('\r');  }
        case 133: break;
        case 63: 
          {  string.append('\"');  }
        case 134: break;
        case 64: 
          {  string.append('\n');  }
        case 135: break;
        case 3: 
        case 9: 
        case 10: 
        case 12: 
        case 13: 
        case 17: 
        case 20: 
        case 21: 
        case 22: 
        case 31: 
        case 32: 
        case 33: 
        case 34: 
          {  emit_warning("Caracter nÃ£o reconhecido '" + yytext() + "' -- ignorado");  }
        case 136: break;
        case 36: 
          {  string = string.append(yytext()); }
        case 137: break;
        case 95: 
          {  return symbol("SWITCH", SWITCH);  }
        case 138: break;
        case 94: 
          {  return symbol("STRUCT", STRUCT);  }
        case 139: break;
        case 5: 
          {  return symbol("SLASH", SLASH);  }
        case 140: break;
        case 108: 
          {  return symbol("FALLTHROUGH", FALLTHROUGH);  }
        case 141: break;
        case 105: 
          {  return symbol("INTERFACE", INTERFACE);  }
        case 142: break;
        case 8: 
          {  return symbol("INT", NUMBER , new Integer(yytext()));  }
        case 143: break;
        case 25: 
          {  return symbol("LPAREN", LPAREN);  }
        case 144: break;
        case 100: 
          {  return symbol("BOOLEAN", BOOLEAN);  }
        case 145: break;
        case 37: 
          { 
									yybegin(YYINITIAL);
									return symbol("STRING", STRING, string.toString());
								 }
        case 146: break;
        case 15: 
          {  return symbol("MINUS", MINUS);  }
        case 147: break;
        case 26: 
          {  return symbol("RLPAREN", RPAREN);  }
        case 148: break;
        case 101: 
          {  return symbol("DEFAULT", DEFAULT);  }
        case 149: break;
        case 24: 
          {  return symbol("SEMICOLON", SEMICOLON);  }
        case 150: break;
        case 23: 
          {  return symbol("COMMA", COMMA);  }
        case 151: break;
        case 28: 
          {  return symbol("RBRACE", RBRACE);  }
        case 152: break;
        case 27: 
          {  return symbol("LBRACE", LBRACE);  }
        case 153: break;
        case 42: 
          {  return symbol("FLOAT", NUMBER , new Float(yytext()));  }
        case 154: break;
        case 29: 
          {  return symbol("LBRACKET", LBRACKET);  }
        case 155: break;
        case 30: 
          {  return symbol("RBRACKET", RBRACKET);  }
        case 156: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     return symbolFactory.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
